### ISSUE TITLE
FEAT: RENT CRUD

### ISSUE THREAD

**Issue by renzocabarios** [renzocabarios/redframe-api#4]
## TODO

- [ ] Add Payment CRUD
- [ ] Add Delivery CRUD
- [ ] Add Rent CRUD

## REFERENCE
![image](https://user-images.githubusercontent.com/72588010/221724586-f3108d87-b0b8-4510-abe5-6d5ecb61c0c0.png)

## NOTES
- KAHIT SKIP MO MUNA YUNG DATE/TIME
